DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  phoneNumber integer,
  profilePic VARCHAR(255)
  note_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,

);