DROP TABLE IF EXISTS favourites CASCADE;
CREATE TABLE favourites (
  id SERIAL PRIMARY KEY,
note_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,
student_id INTEGER REFERENCES students(id) ON DELETE CASCADE,
);