DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE coments (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  note_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,
  student_id INTEGER REFERENCES students(id) ON DELETE CASCADE,
);